ngspice -b -o noiseFirstStart1p2nSeries/data0a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data1a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data2a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data3a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data4a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data5a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data6a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data7a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data8a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data9a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data10a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data11a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data12a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data13a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data14a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data15a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data16a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data17a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data18a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data19a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data20a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data21a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data22a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data23a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data24a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data25a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data26a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data27a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data28a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data29a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data30a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data31a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data32a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data33a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data34a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data35a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data36a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data37a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data38a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data39a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data40a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data41a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data42a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data43a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data44a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data45a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data46a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data47a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data48a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data49a.txt PreLayout/noise_pulsegate3in_1p2nSeriesa.cir
ngspice -b -o noiseFirstStart1p2nSeries/data0b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data1b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data2b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data3b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data4b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data5b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data6b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data7b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data8b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data9b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data10b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data11b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data12b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data13b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data14b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data15b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data16b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data17b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data18b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data19b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data20b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data21b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data22b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data23b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data24b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data25b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data26b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data27b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data28b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data29b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data30b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data31b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data32b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data33b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data34b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data35b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data36b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data37b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data38b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data39b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data40b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data41b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data42b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data43b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data44b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data45b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data46b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data47b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data48b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data49b.txt PreLayout/noise_pulsegate3in_1p2nSeriesb.cir
ngspice -b -o noiseFirstStart1p2nSeries/data0c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data1c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data2c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data3c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data4c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data5c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data6c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data7c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data8c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data9c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data10c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data11c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data12c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data13c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data14c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data15c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data16c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data17c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data18c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data19c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data20c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data21c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data22c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data23c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data24c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data25c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data26c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data27c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data28c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data29c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data30c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data31c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data32c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data33c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data34c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data35c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data36c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data37c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data38c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data39c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data40c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data41c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data42c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data43c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data44c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data45c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data46c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data47c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data48c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data49c.txt PreLayout/noise_pulsegate3in_1p2nSeriesc.cir
ngspice -b -o noiseFirstStart1p2nSeries/data0d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data1d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data2d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data3d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data4d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data5d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data6d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data7d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data8d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data9d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data10d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data11d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data12d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data13d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data14d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data15d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data16d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data17d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data18d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data19d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data20d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data21d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data22d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data23d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data24d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data25d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data26d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data27d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data28d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data29d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data30d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data31d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data32d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data33d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data34d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data35d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data36d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data37d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data38d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data39d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data40d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data41d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data42d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data43d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data44d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data45d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data46d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data47d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data48d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data49d.txt PreLayout/noise_pulsegate3in_1p2nSeriesd.cir
ngspice -b -o noiseFirstStart1p2nSeries/data0e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data1e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data2e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data3e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data4e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data5e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data6e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data7e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data8e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data9e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data10e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data11e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data12e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data13e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data14e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data15e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data16e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data17e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data18e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data19e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data20e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data21e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data22e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data23e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data24e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data25e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data26e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data27e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data28e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data29e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data30e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data31e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data32e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data33e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data34e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data35e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data36e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data37e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data38e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data39e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data40e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data41e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data42e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data43e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data44e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data45e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data46e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data47e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data48e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data49e.txt PreLayout/noise_pulsegate3in_1p2nSeriese.cir
ngspice -b -o noiseFirstStart1p2nSeries/data0f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data1f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data2f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data3f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data4f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data5f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data6f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data7f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data8f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data9f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data10f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data11f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data12f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data13f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data14f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data15f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data16f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data17f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data18f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data19f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data20f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data21f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data22f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data23f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data24f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data25f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data26f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data27f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data28f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data29f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data30f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data31f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data32f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data33f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data34f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data35f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data36f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data37f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data38f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data39f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data40f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data41f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data42f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data43f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data44f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data45f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data46f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data47f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data48f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data49f.txt PreLayout/noise_pulsegate3in_1p2nSeriesf.cir
ngspice -b -o noiseFirstStart1p2nSeries/data0g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data1g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data2g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data3g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data4g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data5g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data6g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data7g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data8g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data9g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data10g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data11g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data12g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data13g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data14g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data15g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data16g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data17g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data18g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data19g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data20g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data21g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data22g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data23g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data24g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data25g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data26g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data27g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data28g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data29g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data30g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data31g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data32g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data33g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data34g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data35g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data36g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data37g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data38g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data39g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data40g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data41g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data42g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data43g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data44g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data45g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data46g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data47g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data48g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data49g.txt PreLayout/noise_pulsegate3in_1p2nSeriesg.cir
ngspice -b -o noiseFirstStart1p2nSeries/data0h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data1h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data2h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data3h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data4h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data5h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data6h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data7h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data8h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data9h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data10h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data11h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data12h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data13h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data14h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data15h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data16h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data17h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data18h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data19h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data20h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data21h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data22h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data23h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data24h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data25h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data26h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data27h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data28h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data29h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data30h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data31h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data32h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data33h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data34h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data35h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data36h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data37h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data38h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data39h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data40h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data41h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data42h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data43h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data44h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data45h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data46h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data47h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data48h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data49h.txt PreLayout/noise_pulsegate3in_1p2nSeriesh.cir
ngspice -b -o noiseFirstStart1p2nSeries/data0i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data1i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data2i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data3i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data4i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data5i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data6i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data7i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data8i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data9i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data10i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data11i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data12i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data13i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data14i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data15i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data16i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data17i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data18i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data19i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data20i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data21i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data22i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data23i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data24i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data25i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data26i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data27i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data28i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data29i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data30i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data31i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data32i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data33i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data34i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data35i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data36i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data37i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data38i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data39i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data40i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data41i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data42i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data43i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data44i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data45i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data46i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data47i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data48i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data49i.txt PreLayout/noise_pulsegate3in_1p2nSeriesi.cir
ngspice -b -o noiseFirstStart1p2nSeries/data0j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data1j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data2j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data3j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data4j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data5j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data6j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data7j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data8j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data9j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data10j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data11j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data12j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data13j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data14j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data15j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data16j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data17j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data18j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data19j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data20j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data21j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data22j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data23j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data24j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data25j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data26j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data27j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data28j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data29j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data30j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data31j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data32j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data33j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data34j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data35j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data36j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data37j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data38j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data39j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data40j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data41j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data42j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data43j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data44j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data45j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data46j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data47j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data48j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data49j.txt PreLayout/noise_pulsegate3in_1p2nSeriesj.cir
ngspice -b -o noiseFirstStart1p2nSeries/data0k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data1k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data2k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data3k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data4k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data5k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data6k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data7k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data8k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data9k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data10k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data11k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data12k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data13k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data14k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data15k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data16k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data17k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data18k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data19k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data20k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data21k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data22k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data23k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data24k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data25k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data26k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data27k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data28k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data29k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data30k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data31k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data32k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data33k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data34k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data35k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data36k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data37k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data38k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data39k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data40k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data41k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data42k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data43k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data44k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data45k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data46k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data47k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data48k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data49k.txt PreLayout/noise_pulsegate3in_1p2nSeriesk.cir
ngspice -b -o noiseFirstStart1p2nSeries/data0l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data1l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data2l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data3l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data4l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data5l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data6l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data7l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data8l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data9l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data10l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data11l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data12l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data13l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data14l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data15l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data16l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data17l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data18l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data19l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data20l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data21l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data22l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data23l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data24l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data25l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data26l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data27l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data28l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data29l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data30l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data31l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data32l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data33l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data34l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data35l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data36l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data37l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data38l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data39l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data40l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data41l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data42l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data43l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data44l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data45l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data46l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data47l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data48l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data49l.txt PreLayout/noise_pulsegate3in_1p2nSeriesl.cir
ngspice -b -o noiseFirstStart1p2nSeries/data0m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data1m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data2m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data3m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data4m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data5m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data6m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data7m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data8m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data9m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data10m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data11m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data12m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data13m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data14m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data15m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data16m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data17m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data18m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data19m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data20m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data21m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data22m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data23m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data24m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data25m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data26m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data27m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data28m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data29m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data30m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data31m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data32m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data33m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data34m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data35m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data36m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data37m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data38m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data39m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data40m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data41m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data42m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data43m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data44m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data45m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data46m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data47m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data48m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data49m.txt PreLayout/noise_pulsegate3in_1p2nSeriesm.cir
ngspice -b -o noiseFirstStart1p2nSeries/data0n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data1n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data2n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data3n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data4n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data5n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data6n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data7n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data8n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data9n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data10n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data11n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data12n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data13n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data14n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data15n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data16n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data17n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data18n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data19n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data20n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data21n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data22n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data23n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data24n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data25n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data26n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data27n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data28n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data29n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data30n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data31n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data32n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data33n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data34n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data35n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data36n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data37n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data38n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data39n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data40n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data41n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data42n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data43n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data44n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data45n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data46n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data47n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data48n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data49n.txt PreLayout/noise_pulsegate3in_1p2nSeriesn.cir
ngspice -b -o noiseFirstStart1p2nSeries/data0o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data1o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data2o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data3o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data4o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data5o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data6o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data7o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data8o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data9o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data10o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data11o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data12o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data13o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data14o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data15o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data16o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data17o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data18o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data19o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data20o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data21o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data22o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data23o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data24o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data25o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data26o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data27o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data28o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data29o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data30o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data31o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data32o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data33o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data34o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data35o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data36o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data37o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data38o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data39o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data40o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data41o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data42o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data43o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data44o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data45o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data46o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data47o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data48o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data49o.txt PreLayout/noise_pulsegate3in_1p2nSerieso.cir
ngspice -b -o noiseFirstStart1p2nSeries/data0p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data1p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data2p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data3p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data4p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data5p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data6p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data7p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data8p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data9p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data10p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data11p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data12p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data13p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data14p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data15p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data16p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data17p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data18p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data19p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data20p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data21p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data22p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data23p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data24p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data25p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data26p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data27p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data28p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data29p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data30p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data31p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data32p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data33p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data34p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data35p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data36p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data37p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data38p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data39p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data40p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data41p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data42p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data43p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data44p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data45p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data46p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data47p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data48p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data49p.txt PreLayout/noise_pulsegate3in_1p2nSeriesp.cir
ngspice -b -o noiseFirstStart1p2nSeries/data0q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data1q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data2q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data3q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data4q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data5q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data6q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data7q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data8q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data9q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data10q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data11q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data12q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data13q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data14q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data15q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data16q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data17q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data18q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data19q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data20q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data21q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data22q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data23q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data24q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data25q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data26q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data27q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data28q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data29q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data30q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data31q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data32q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data33q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data34q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data35q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data36q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data37q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data38q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data39q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data40q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data41q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data42q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data43q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data44q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data45q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data46q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data47q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data48q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data49q.txt PreLayout/noise_pulsegate3in_1p2nSeriesq.cir
ngspice -b -o noiseFirstStart1p2nSeries/data0r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data1r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data2r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data3r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data4r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data5r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data6r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data7r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data8r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data9r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data10r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data11r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data12r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data13r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data14r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data15r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data16r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data17r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data18r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data19r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data20r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data21r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data22r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data23r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data24r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data25r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data26r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data27r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data28r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data29r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data30r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data31r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data32r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data33r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data34r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data35r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data36r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data37r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data38r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data39r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data40r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data41r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data42r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data43r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data44r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data45r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data46r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data47r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data48r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
ngspice -b -o noiseFirstStart1p2nSeries/data49r.txt PreLayout/noise_pulsegate3in_1p2nSeriesr.cir
