ngspice -b -o noiseFirstStart\data0a.txt PreLayout\noise_pulsegate1a.cir
ngspice -b -o noiseFirstStart\data1a.txt PreLayout\noise_pulsegate1a.cir
ngspice -b -o noiseFirstStart\data2a.txt PreLayout\noise_pulsegate1a.cir
ngspice -b -o noiseFirstStart\data3a.txt PreLayout\noise_pulsegate1a.cir
ngspice -b -o noiseFirstStart\data4a.txt PreLayout\noise_pulsegate1a.cir
ngspice -b -o noiseFirstStart\data5a.txt PreLayout\noise_pulsegate1a.cir
ngspice -b -o noiseFirstStart\data6a.txt PreLayout\noise_pulsegate1a.cir
ngspice -b -o noiseFirstStart\data7a.txt PreLayout\noise_pulsegate1a.cir
ngspice -b -o noiseFirstStart\data8a.txt PreLayout\noise_pulsegate1a.cir
ngspice -b -o noiseFirstStart\data9a.txt PreLayout\noise_pulsegate1a.cir
ngspice -b -o noiseFirstStart\data0b.txt PreLayout\noise_pulsegate1b.cir
ngspice -b -o noiseFirstStart\data1b.txt PreLayout\noise_pulsegate1b.cir
ngspice -b -o noiseFirstStart\data2b.txt PreLayout\noise_pulsegate1b.cir
ngspice -b -o noiseFirstStart\data3b.txt PreLayout\noise_pulsegate1b.cir
ngspice -b -o noiseFirstStart\data4b.txt PreLayout\noise_pulsegate1b.cir
ngspice -b -o noiseFirstStart\data5b.txt PreLayout\noise_pulsegate1b.cir
ngspice -b -o noiseFirstStart\data6b.txt PreLayout\noise_pulsegate1b.cir
ngspice -b -o noiseFirstStart\data7b.txt PreLayout\noise_pulsegate1b.cir
ngspice -b -o noiseFirstStart\data8b.txt PreLayout\noise_pulsegate1b.cir
ngspice -b -o noiseFirstStart\data9b.txt PreLayout\noise_pulsegate1b.cir
ngspice -b -o noiseFirstStart\data0c.txt PreLayout\noise_pulsegate1c.cir
ngspice -b -o noiseFirstStart\data1c.txt PreLayout\noise_pulsegate1c.cir
ngspice -b -o noiseFirstStart\data2c.txt PreLayout\noise_pulsegate1c.cir
ngspice -b -o noiseFirstStart\data3c.txt PreLayout\noise_pulsegate1c.cir
ngspice -b -o noiseFirstStart\data4c.txt PreLayout\noise_pulsegate1c.cir
ngspice -b -o noiseFirstStart\data5c.txt PreLayout\noise_pulsegate1c.cir
ngspice -b -o noiseFirstStart\data6c.txt PreLayout\noise_pulsegate1c.cir
ngspice -b -o noiseFirstStart\data7c.txt PreLayout\noise_pulsegate1c.cir
ngspice -b -o noiseFirstStart\data8c.txt PreLayout\noise_pulsegate1c.cir
ngspice -b -o noiseFirstStart\data9c.txt PreLayout\noise_pulsegate1c.cir
ngspice -b -o noiseFirstStart\data0d.txt PreLayout\noise_pulsegate1d.cir
ngspice -b -o noiseFirstStart\data1d.txt PreLayout\noise_pulsegate1d.cir
ngspice -b -o noiseFirstStart\data2d.txt PreLayout\noise_pulsegate1d.cir
ngspice -b -o noiseFirstStart\data3d.txt PreLayout\noise_pulsegate1d.cir
ngspice -b -o noiseFirstStart\data4d.txt PreLayout\noise_pulsegate1d.cir
ngspice -b -o noiseFirstStart\data5d.txt PreLayout\noise_pulsegate1d.cir
ngspice -b -o noiseFirstStart\data6d.txt PreLayout\noise_pulsegate1d.cir
ngspice -b -o noiseFirstStart\data7d.txt PreLayout\noise_pulsegate1d.cir
ngspice -b -o noiseFirstStart\data8d.txt PreLayout\noise_pulsegate1d.cir
ngspice -b -o noiseFirstStart\data9d.txt PreLayout\noise_pulsegate1d.cir
ngspice -b -o noiseFirstStart\data0e.txt PreLayout\noise_pulsegate1e.cir
ngspice -b -o noiseFirstStart\data1e.txt PreLayout\noise_pulsegate1e.cir
ngspice -b -o noiseFirstStart\data2e.txt PreLayout\noise_pulsegate1e.cir
ngspice -b -o noiseFirstStart\data3e.txt PreLayout\noise_pulsegate1e.cir
ngspice -b -o noiseFirstStart\data4e.txt PreLayout\noise_pulsegate1e.cir
ngspice -b -o noiseFirstStart\data5e.txt PreLayout\noise_pulsegate1e.cir
ngspice -b -o noiseFirstStart\data6e.txt PreLayout\noise_pulsegate1e.cir
ngspice -b -o noiseFirstStart\data7e.txt PreLayout\noise_pulsegate1e.cir
ngspice -b -o noiseFirstStart\data8e.txt PreLayout\noise_pulsegate1e.cir
ngspice -b -o noiseFirstStart\data9e.txt PreLayout\noise_pulsegate1e.cir
ngspice -b -o noiseFirstStart\data0f.txt PreLayout\noise_pulsegate1f.cir
ngspice -b -o noiseFirstStart\data1f.txt PreLayout\noise_pulsegate1f.cir
ngspice -b -o noiseFirstStart\data2f.txt PreLayout\noise_pulsegate1f.cir
ngspice -b -o noiseFirstStart\data3f.txt PreLayout\noise_pulsegate1f.cir
ngspice -b -o noiseFirstStart\data4f.txt PreLayout\noise_pulsegate1f.cir
ngspice -b -o noiseFirstStart\data5f.txt PreLayout\noise_pulsegate1f.cir
ngspice -b -o noiseFirstStart\data6f.txt PreLayout\noise_pulsegate1f.cir
ngspice -b -o noiseFirstStart\data7f.txt PreLayout\noise_pulsegate1f.cir
ngspice -b -o noiseFirstStart\data8f.txt PreLayout\noise_pulsegate1f.cir
ngspice -b -o noiseFirstStart\data9f.txt PreLayout\noise_pulsegate1f.cir
ngspice -b -o noiseFirstStart\data0g.txt PreLayout\noise_pulsegate1g.cir
ngspice -b -o noiseFirstStart\data1g.txt PreLayout\noise_pulsegate1g.cir
ngspice -b -o noiseFirstStart\data2g.txt PreLayout\noise_pulsegate1g.cir
ngspice -b -o noiseFirstStart\data3g.txt PreLayout\noise_pulsegate1g.cir
ngspice -b -o noiseFirstStart\data4g.txt PreLayout\noise_pulsegate1g.cir
ngspice -b -o noiseFirstStart\data5g.txt PreLayout\noise_pulsegate1g.cir
ngspice -b -o noiseFirstStart\data6g.txt PreLayout\noise_pulsegate1g.cir
ngspice -b -o noiseFirstStart\data7g.txt PreLayout\noise_pulsegate1g.cir
ngspice -b -o noiseFirstStart\data8g.txt PreLayout\noise_pulsegate1g.cir
ngspice -b -o noiseFirstStart\data9g.txt PreLayout\noise_pulsegate1g.cir
ngspice -b -o noiseFirstStart\data0h.txt PreLayout\noise_pulsegate1h.cir
ngspice -b -o noiseFirstStart\data1h.txt PreLayout\noise_pulsegate1h.cir
ngspice -b -o noiseFirstStart\data2h.txt PreLayout\noise_pulsegate1h.cir
ngspice -b -o noiseFirstStart\data3h.txt PreLayout\noise_pulsegate1h.cir
ngspice -b -o noiseFirstStart\data4h.txt PreLayout\noise_pulsegate1h.cir
ngspice -b -o noiseFirstStart\data5h.txt PreLayout\noise_pulsegate1h.cir
ngspice -b -o noiseFirstStart\data6h.txt PreLayout\noise_pulsegate1h.cir
ngspice -b -o noiseFirstStart\data7h.txt PreLayout\noise_pulsegate1h.cir
ngspice -b -o noiseFirstStart\data8h.txt PreLayout\noise_pulsegate1h.cir
ngspice -b -o noiseFirstStart\data9h.txt PreLayout\noise_pulsegate1h.cir
ngspice -b -o noiseFirstStart\data0i.txt PreLayout\noise_pulsegate1i.cir
ngspice -b -o noiseFirstStart\data1i.txt PreLayout\noise_pulsegate1i.cir
ngspice -b -o noiseFirstStart\data2i.txt PreLayout\noise_pulsegate1i.cir
ngspice -b -o noiseFirstStart\data3i.txt PreLayout\noise_pulsegate1i.cir
ngspice -b -o noiseFirstStart\data4i.txt PreLayout\noise_pulsegate1i.cir
ngspice -b -o noiseFirstStart\data5i.txt PreLayout\noise_pulsegate1i.cir
ngspice -b -o noiseFirstStart\data6i.txt PreLayout\noise_pulsegate1i.cir
ngspice -b -o noiseFirstStart\data7i.txt PreLayout\noise_pulsegate1i.cir
ngspice -b -o noiseFirstStart\data8i.txt PreLayout\noise_pulsegate1i.cir
ngspice -b -o noiseFirstStart\data9i.txt PreLayout\noise_pulsegate1i.cir
ngspice -b -o noiseFirstStart\data0j.txt PreLayout\noise_pulsegate1j.cir
ngspice -b -o noiseFirstStart\data1j.txt PreLayout\noise_pulsegate1j.cir
ngspice -b -o noiseFirstStart\data2j.txt PreLayout\noise_pulsegate1j.cir
ngspice -b -o noiseFirstStart\data3j.txt PreLayout\noise_pulsegate1j.cir
ngspice -b -o noiseFirstStart\data4j.txt PreLayout\noise_pulsegate1j.cir
ngspice -b -o noiseFirstStart\data5j.txt PreLayout\noise_pulsegate1j.cir
ngspice -b -o noiseFirstStart\data6j.txt PreLayout\noise_pulsegate1j.cir
ngspice -b -o noiseFirstStart\data7j.txt PreLayout\noise_pulsegate1j.cir
ngspice -b -o noiseFirstStart\data8j.txt PreLayout\noise_pulsegate1j.cir
ngspice -b -o noiseFirstStart\data9j.txt PreLayout\noise_pulsegate1j.cir
ngspice -b -o noiseFirstStart\data0k.txt PreLayout\noise_pulsegate1k.cir
ngspice -b -o noiseFirstStart\data1k.txt PreLayout\noise_pulsegate1k.cir
ngspice -b -o noiseFirstStart\data2k.txt PreLayout\noise_pulsegate1k.cir
ngspice -b -o noiseFirstStart\data3k.txt PreLayout\noise_pulsegate1k.cir
ngspice -b -o noiseFirstStart\data4k.txt PreLayout\noise_pulsegate1k.cir
ngspice -b -o noiseFirstStart\data5k.txt PreLayout\noise_pulsegate1k.cir
ngspice -b -o noiseFirstStart\data6k.txt PreLayout\noise_pulsegate1k.cir
ngspice -b -o noiseFirstStart\data7k.txt PreLayout\noise_pulsegate1k.cir
ngspice -b -o noiseFirstStart\data8k.txt PreLayout\noise_pulsegate1k.cir
ngspice -b -o noiseFirstStart\data9k.txt PreLayout\noise_pulsegate1k.cir
ngspice -b -o noiseFirstStart\data0l.txt PreLayout\noise_pulsegate1l.cir
ngspice -b -o noiseFirstStart\data1l.txt PreLayout\noise_pulsegate1l.cir
ngspice -b -o noiseFirstStart\data2l.txt PreLayout\noise_pulsegate1l.cir
ngspice -b -o noiseFirstStart\data3l.txt PreLayout\noise_pulsegate1l.cir
ngspice -b -o noiseFirstStart\data4l.txt PreLayout\noise_pulsegate1l.cir
ngspice -b -o noiseFirstStart\data5l.txt PreLayout\noise_pulsegate1l.cir
ngspice -b -o noiseFirstStart\data6l.txt PreLayout\noise_pulsegate1l.cir
ngspice -b -o noiseFirstStart\data7l.txt PreLayout\noise_pulsegate1l.cir
ngspice -b -o noiseFirstStart\data8l.txt PreLayout\noise_pulsegate1l.cir
ngspice -b -o noiseFirstStart\data9l.txt PreLayout\noise_pulsegate1l.cir
ngspice -b -o noiseFirstStart\data0m.txt PreLayout\noise_pulsegate1m.cir
ngspice -b -o noiseFirstStart\data1m.txt PreLayout\noise_pulsegate1m.cir
ngspice -b -o noiseFirstStart\data2m.txt PreLayout\noise_pulsegate1m.cir
ngspice -b -o noiseFirstStart\data3m.txt PreLayout\noise_pulsegate1m.cir
ngspice -b -o noiseFirstStart\data4m.txt PreLayout\noise_pulsegate1m.cir
ngspice -b -o noiseFirstStart\data5m.txt PreLayout\noise_pulsegate1m.cir
ngspice -b -o noiseFirstStart\data6m.txt PreLayout\noise_pulsegate1m.cir
ngspice -b -o noiseFirstStart\data7m.txt PreLayout\noise_pulsegate1m.cir
ngspice -b -o noiseFirstStart\data8m.txt PreLayout\noise_pulsegate1m.cir
ngspice -b -o noiseFirstStart\data9m.txt PreLayout\noise_pulsegate1m.cir
ngspice -b -o noiseFirstStart\data0n.txt PreLayout\noise_pulsegate1n.cir
ngspice -b -o noiseFirstStart\data1n.txt PreLayout\noise_pulsegate1n.cir
ngspice -b -o noiseFirstStart\data2n.txt PreLayout\noise_pulsegate1n.cir
ngspice -b -o noiseFirstStart\data3n.txt PreLayout\noise_pulsegate1n.cir
ngspice -b -o noiseFirstStart\data4n.txt PreLayout\noise_pulsegate1n.cir
ngspice -b -o noiseFirstStart\data5n.txt PreLayout\noise_pulsegate1n.cir
ngspice -b -o noiseFirstStart\data6n.txt PreLayout\noise_pulsegate1n.cir
ngspice -b -o noiseFirstStart\data7n.txt PreLayout\noise_pulsegate1n.cir
ngspice -b -o noiseFirstStart\data8n.txt PreLayout\noise_pulsegate1n.cir
ngspice -b -o noiseFirstStart\data9n.txt PreLayout\noise_pulsegate1n.cir
ngspice -b -o noiseFirstStart\data0o.txt PreLayout\noise_pulsegate1o.cir
ngspice -b -o noiseFirstStart\data1o.txt PreLayout\noise_pulsegate1o.cir
ngspice -b -o noiseFirstStart\data2o.txt PreLayout\noise_pulsegate1o.cir
ngspice -b -o noiseFirstStart\data3o.txt PreLayout\noise_pulsegate1o.cir
ngspice -b -o noiseFirstStart\data4o.txt PreLayout\noise_pulsegate1o.cir
ngspice -b -o noiseFirstStart\data5o.txt PreLayout\noise_pulsegate1o.cir
ngspice -b -o noiseFirstStart\data6o.txt PreLayout\noise_pulsegate1o.cir
ngspice -b -o noiseFirstStart\data7o.txt PreLayout\noise_pulsegate1o.cir
ngspice -b -o noiseFirstStart\data8o.txt PreLayout\noise_pulsegate1o.cir
ngspice -b -o noiseFirstStart\data9o.txt PreLayout\noise_pulsegate1o.cir
