ngspice -b -o exp_mixingTime/circuit9/data0a.txt PreLayout/phase_exp_mixing_time_a.cir
ngspice -b -o exp_mixingTime/circuit9/data0b.txt PreLayout/phase_exp_mixing_time_b.cir
ngspice -b -o exp_mixingTime/circuit9/data0c.txt PreLayout/phase_exp_mixing_time_c.cir
ngspice -b -o exp_mixingTime/circuit9/data0d.txt PreLayout/phase_exp_mixing_time_d.cir
ngspice -b -o exp_mixingTime/circuit9/data0e.txt PreLayout/phase_exp_mixing_time_e.cir
ngspice -b -o exp_mixingTime/circuit9/data0f.txt PreLayout/phase_exp_mixing_time_f.cir
ngspice -b -o exp_mixingTime/circuit9/data0g.txt PreLayout/phase_exp_mixing_time_g.cir
ngspice -b -o exp_mixingTime/circuit9/data0h.txt PreLayout/phase_exp_mixing_time_h.cir
ngspice -b -o exp_mixingTime/circuit9/data0i.txt PreLayout/phase_exp_mixing_time_i.cir
ngspice -b -o exp_mixingTime/circuit9/data0j.txt PreLayout/phase_exp_mixing_time_j.cir
ngspice -b -o exp_mixingTime/circuit9/data0k.txt PreLayout/phase_exp_mixing_time_k.cir
ngspice -b -o exp_mixingTime/circuit9/data0l.txt PreLayout/phase_exp_mixing_time_l.cir
ngspice -b -o exp_mixingTime/circuit9/data0m.txt PreLayout/phase_exp_mixing_time_m.cir
ngspice -b -o exp_mixingTime/circuit9/data0n.txt PreLayout/phase_exp_mixing_time_n.cir
ngspice -b -o exp_mixingTime/circuit9/data0o.txt PreLayout/phase_exp_mixing_time_o.cir
