ngspice -b -o noiseMeanFirstStart/data0a.txt PreLayout/mean_pulsegate1a.cir
ngspice -b -o noiseMeanFirstStart/data1a.txt PreLayout/mean_pulsegate1a.cir
ngspice -b -o noiseMeanFirstStart/data2a.txt PreLayout/mean_pulsegate1a.cir
ngspice -b -o noiseMeanFirstStart/data3a.txt PreLayout/mean_pulsegate1a.cir
ngspice -b -o noiseMeanFirstStart/data4a.txt PreLayout/mean_pulsegate1a.cir
ngspice -b -o noiseMeanFirstStart/data5a.txt PreLayout/mean_pulsegate1a.cir
ngspice -b -o noiseMeanFirstStart/data6a.txt PreLayout/mean_pulsegate1a.cir
ngspice -b -o noiseMeanFirstStart/data7a.txt PreLayout/mean_pulsegate1a.cir
ngspice -b -o noiseMeanFirstStart/data8a.txt PreLayout/mean_pulsegate1a.cir
ngspice -b -o noiseMeanFirstStart/data9a.txt PreLayout/mean_pulsegate1a.cir
ngspice -b -o noiseMeanFirstStart/data0b.txt PreLayout/mean_pulsegate1b.cir
ngspice -b -o noiseMeanFirstStart/data1b.txt PreLayout/mean_pulsegate1b.cir
ngspice -b -o noiseMeanFirstStart/data2b.txt PreLayout/mean_pulsegate1b.cir
ngspice -b -o noiseMeanFirstStart/data3b.txt PreLayout/mean_pulsegate1b.cir
ngspice -b -o noiseMeanFirstStart/data4b.txt PreLayout/mean_pulsegate1b.cir
ngspice -b -o noiseMeanFirstStart/data5b.txt PreLayout/mean_pulsegate1b.cir
ngspice -b -o noiseMeanFirstStart/data6b.txt PreLayout/mean_pulsegate1b.cir
ngspice -b -o noiseMeanFirstStart/data7b.txt PreLayout/mean_pulsegate1b.cir
ngspice -b -o noiseMeanFirstStart/data8b.txt PreLayout/mean_pulsegate1b.cir
ngspice -b -o noiseMeanFirstStart/data9b.txt PreLayout/mean_pulsegate1b.cir
ngspice -b -o noiseMeanFirstStart/data0c.txt PreLayout/mean_pulsegate1c.cir
ngspice -b -o noiseMeanFirstStart/data1c.txt PreLayout/mean_pulsegate1c.cir
ngspice -b -o noiseMeanFirstStart/data2c.txt PreLayout/mean_pulsegate1c.cir
ngspice -b -o noiseMeanFirstStart/data3c.txt PreLayout/mean_pulsegate1c.cir
ngspice -b -o noiseMeanFirstStart/data4c.txt PreLayout/mean_pulsegate1c.cir
ngspice -b -o noiseMeanFirstStart/data5c.txt PreLayout/mean_pulsegate1c.cir
ngspice -b -o noiseMeanFirstStart/data6c.txt PreLayout/mean_pulsegate1c.cir
ngspice -b -o noiseMeanFirstStart/data7c.txt PreLayout/mean_pulsegate1c.cir
ngspice -b -o noiseMeanFirstStart/data8c.txt PreLayout/mean_pulsegate1c.cir
ngspice -b -o noiseMeanFirstStart/data9c.txt PreLayout/mean_pulsegate1c.cir
ngspice -b -o noiseMeanFirstStart/data0d.txt PreLayout/mean_pulsegate1d.cir
ngspice -b -o noiseMeanFirstStart/data1d.txt PreLayout/mean_pulsegate1d.cir
ngspice -b -o noiseMeanFirstStart/data2d.txt PreLayout/mean_pulsegate1d.cir
ngspice -b -o noiseMeanFirstStart/data3d.txt PreLayout/mean_pulsegate1d.cir
ngspice -b -o noiseMeanFirstStart/data4d.txt PreLayout/mean_pulsegate1d.cir
ngspice -b -o noiseMeanFirstStart/data5d.txt PreLayout/mean_pulsegate1d.cir
ngspice -b -o noiseMeanFirstStart/data6d.txt PreLayout/mean_pulsegate1d.cir
ngspice -b -o noiseMeanFirstStart/data7d.txt PreLayout/mean_pulsegate1d.cir
ngspice -b -o noiseMeanFirstStart/data8d.txt PreLayout/mean_pulsegate1d.cir
ngspice -b -o noiseMeanFirstStart/data9d.txt PreLayout/mean_pulsegate1d.cir
ngspice -b -o noiseMeanFirstStart/data0e.txt PreLayout/mean_pulsegate1e.cir
ngspice -b -o noiseMeanFirstStart/data1e.txt PreLayout/mean_pulsegate1e.cir
ngspice -b -o noiseMeanFirstStart/data2e.txt PreLayout/mean_pulsegate1e.cir
ngspice -b -o noiseMeanFirstStart/data3e.txt PreLayout/mean_pulsegate1e.cir
ngspice -b -o noiseMeanFirstStart/data4e.txt PreLayout/mean_pulsegate1e.cir
ngspice -b -o noiseMeanFirstStart/data5e.txt PreLayout/mean_pulsegate1e.cir
ngspice -b -o noiseMeanFirstStart/data6e.txt PreLayout/mean_pulsegate1e.cir
ngspice -b -o noiseMeanFirstStart/data7e.txt PreLayout/mean_pulsegate1e.cir
ngspice -b -o noiseMeanFirstStart/data8e.txt PreLayout/mean_pulsegate1e.cir
ngspice -b -o noiseMeanFirstStart/data9e.txt PreLayout/mean_pulsegate1e.cir
ngspice -b -o noiseMeanFirstStart/data0f.txt PreLayout/mean_pulsegate1f.cir
ngspice -b -o noiseMeanFirstStart/data1f.txt PreLayout/mean_pulsegate1f.cir
ngspice -b -o noiseMeanFirstStart/data2f.txt PreLayout/mean_pulsegate1f.cir
ngspice -b -o noiseMeanFirstStart/data3f.txt PreLayout/mean_pulsegate1f.cir
ngspice -b -o noiseMeanFirstStart/data4f.txt PreLayout/mean_pulsegate1f.cir
ngspice -b -o noiseMeanFirstStart/data5f.txt PreLayout/mean_pulsegate1f.cir
ngspice -b -o noiseMeanFirstStart/data6f.txt PreLayout/mean_pulsegate1f.cir
ngspice -b -o noiseMeanFirstStart/data7f.txt PreLayout/mean_pulsegate1f.cir
ngspice -b -o noiseMeanFirstStart/data8f.txt PreLayout/mean_pulsegate1f.cir
ngspice -b -o noiseMeanFirstStart/data9f.txt PreLayout/mean_pulsegate1f.cir
ngspice -b -o noiseMeanFirstStart/data0g.txt PreLayout/mean_pulsegate1g.cir
ngspice -b -o noiseMeanFirstStart/data1g.txt PreLayout/mean_pulsegate1g.cir
ngspice -b -o noiseMeanFirstStart/data2g.txt PreLayout/mean_pulsegate1g.cir
ngspice -b -o noiseMeanFirstStart/data3g.txt PreLayout/mean_pulsegate1g.cir
ngspice -b -o noiseMeanFirstStart/data4g.txt PreLayout/mean_pulsegate1g.cir
ngspice -b -o noiseMeanFirstStart/data5g.txt PreLayout/mean_pulsegate1g.cir
ngspice -b -o noiseMeanFirstStart/data6g.txt PreLayout/mean_pulsegate1g.cir
ngspice -b -o noiseMeanFirstStart/data7g.txt PreLayout/mean_pulsegate1g.cir
ngspice -b -o noiseMeanFirstStart/data8g.txt PreLayout/mean_pulsegate1g.cir
ngspice -b -o noiseMeanFirstStart/data9g.txt PreLayout/mean_pulsegate1g.cir
ngspice -b -o noiseMeanFirstStart/data0h.txt PreLayout/mean_pulsegate1h.cir
ngspice -b -o noiseMeanFirstStart/data1h.txt PreLayout/mean_pulsegate1h.cir
ngspice -b -o noiseMeanFirstStart/data2h.txt PreLayout/mean_pulsegate1h.cir
ngspice -b -o noiseMeanFirstStart/data3h.txt PreLayout/mean_pulsegate1h.cir
ngspice -b -o noiseMeanFirstStart/data4h.txt PreLayout/mean_pulsegate1h.cir
ngspice -b -o noiseMeanFirstStart/data5h.txt PreLayout/mean_pulsegate1h.cir
ngspice -b -o noiseMeanFirstStart/data6h.txt PreLayout/mean_pulsegate1h.cir
ngspice -b -o noiseMeanFirstStart/data7h.txt PreLayout/mean_pulsegate1h.cir
ngspice -b -o noiseMeanFirstStart/data8h.txt PreLayout/mean_pulsegate1h.cir
ngspice -b -o noiseMeanFirstStart/data9h.txt PreLayout/mean_pulsegate1h.cir
ngspice -b -o noiseMeanFirstStart/data0i.txt PreLayout/mean_pulsegate1i.cir
ngspice -b -o noiseMeanFirstStart/data1i.txt PreLayout/mean_pulsegate1i.cir
ngspice -b -o noiseMeanFirstStart/data2i.txt PreLayout/mean_pulsegate1i.cir
ngspice -b -o noiseMeanFirstStart/data3i.txt PreLayout/mean_pulsegate1i.cir
ngspice -b -o noiseMeanFirstStart/data4i.txt PreLayout/mean_pulsegate1i.cir
ngspice -b -o noiseMeanFirstStart/data5i.txt PreLayout/mean_pulsegate1i.cir
ngspice -b -o noiseMeanFirstStart/data6i.txt PreLayout/mean_pulsegate1i.cir
ngspice -b -o noiseMeanFirstStart/data7i.txt PreLayout/mean_pulsegate1i.cir
ngspice -b -o noiseMeanFirstStart/data8i.txt PreLayout/mean_pulsegate1i.cir
ngspice -b -o noiseMeanFirstStart/data9i.txt PreLayout/mean_pulsegate1i.cir
ngspice -b -o noiseMeanFirstStart/data0j.txt PreLayout/mean_pulsegate1j.cir
ngspice -b -o noiseMeanFirstStart/data1j.txt PreLayout/mean_pulsegate1j.cir
ngspice -b -o noiseMeanFirstStart/data2j.txt PreLayout/mean_pulsegate1j.cir
ngspice -b -o noiseMeanFirstStart/data3j.txt PreLayout/mean_pulsegate1j.cir
ngspice -b -o noiseMeanFirstStart/data4j.txt PreLayout/mean_pulsegate1j.cir
ngspice -b -o noiseMeanFirstStart/data5j.txt PreLayout/mean_pulsegate1j.cir
ngspice -b -o noiseMeanFirstStart/data6j.txt PreLayout/mean_pulsegate1j.cir
ngspice -b -o noiseMeanFirstStart/data7j.txt PreLayout/mean_pulsegate1j.cir
ngspice -b -o noiseMeanFirstStart/data8j.txt PreLayout/mean_pulsegate1j.cir
ngspice -b -o noiseMeanFirstStart/data9j.txt PreLayout/mean_pulsegate1j.cir
ngspice -b -o noiseMeanFirstStart/data0k.txt PreLayout/mean_pulsegate1k.cir
ngspice -b -o noiseMeanFirstStart/data1k.txt PreLayout/mean_pulsegate1k.cir
ngspice -b -o noiseMeanFirstStart/data2k.txt PreLayout/mean_pulsegate1k.cir
ngspice -b -o noiseMeanFirstStart/data3k.txt PreLayout/mean_pulsegate1k.cir
ngspice -b -o noiseMeanFirstStart/data4k.txt PreLayout/mean_pulsegate1k.cir
ngspice -b -o noiseMeanFirstStart/data5k.txt PreLayout/mean_pulsegate1k.cir
ngspice -b -o noiseMeanFirstStart/data6k.txt PreLayout/mean_pulsegate1k.cir
ngspice -b -o noiseMeanFirstStart/data7k.txt PreLayout/mean_pulsegate1k.cir
ngspice -b -o noiseMeanFirstStart/data8k.txt PreLayout/mean_pulsegate1k.cir
ngspice -b -o noiseMeanFirstStart/data9k.txt PreLayout/mean_pulsegate1k.cir
ngspice -b -o noiseMeanFirstStart/data0l.txt PreLayout/mean_pulsegate1l.cir
ngspice -b -o noiseMeanFirstStart/data1l.txt PreLayout/mean_pulsegate1l.cir
ngspice -b -o noiseMeanFirstStart/data2l.txt PreLayout/mean_pulsegate1l.cir
ngspice -b -o noiseMeanFirstStart/data3l.txt PreLayout/mean_pulsegate1l.cir
ngspice -b -o noiseMeanFirstStart/data4l.txt PreLayout/mean_pulsegate1l.cir
ngspice -b -o noiseMeanFirstStart/data5l.txt PreLayout/mean_pulsegate1l.cir
ngspice -b -o noiseMeanFirstStart/data6l.txt PreLayout/mean_pulsegate1l.cir
ngspice -b -o noiseMeanFirstStart/data7l.txt PreLayout/mean_pulsegate1l.cir
ngspice -b -o noiseMeanFirstStart/data8l.txt PreLayout/mean_pulsegate1l.cir
ngspice -b -o noiseMeanFirstStart/data9l.txt PreLayout/mean_pulsegate1l.cir
ngspice -b -o noiseMeanFirstStart/data0m.txt PreLayout/mean_pulsegate1m.cir
ngspice -b -o noiseMeanFirstStart/data1m.txt PreLayout/mean_pulsegate1m.cir
ngspice -b -o noiseMeanFirstStart/data2m.txt PreLayout/mean_pulsegate1m.cir
ngspice -b -o noiseMeanFirstStart/data3m.txt PreLayout/mean_pulsegate1m.cir
ngspice -b -o noiseMeanFirstStart/data4m.txt PreLayout/mean_pulsegate1m.cir
ngspice -b -o noiseMeanFirstStart/data5m.txt PreLayout/mean_pulsegate1m.cir
ngspice -b -o noiseMeanFirstStart/data6m.txt PreLayout/mean_pulsegate1m.cir
ngspice -b -o noiseMeanFirstStart/data7m.txt PreLayout/mean_pulsegate1m.cir
ngspice -b -o noiseMeanFirstStart/data8m.txt PreLayout/mean_pulsegate1m.cir
ngspice -b -o noiseMeanFirstStart/data9m.txt PreLayout/mean_pulsegate1m.cir
ngspice -b -o noiseMeanFirstStart/data0n.txt PreLayout/mean_pulsegate1n.cir
ngspice -b -o noiseMeanFirstStart/data1n.txt PreLayout/mean_pulsegate1n.cir
ngspice -b -o noiseMeanFirstStart/data2n.txt PreLayout/mean_pulsegate1n.cir
ngspice -b -o noiseMeanFirstStart/data3n.txt PreLayout/mean_pulsegate1n.cir
ngspice -b -o noiseMeanFirstStart/data4n.txt PreLayout/mean_pulsegate1n.cir
ngspice -b -o noiseMeanFirstStart/data5n.txt PreLayout/mean_pulsegate1n.cir
ngspice -b -o noiseMeanFirstStart/data6n.txt PreLayout/mean_pulsegate1n.cir
ngspice -b -o noiseMeanFirstStart/data7n.txt PreLayout/mean_pulsegate1n.cir
ngspice -b -o noiseMeanFirstStart/data8n.txt PreLayout/mean_pulsegate1n.cir
ngspice -b -o noiseMeanFirstStart/data9n.txt PreLayout/mean_pulsegate1n.cir
ngspice -b -o noiseMeanFirstStart/data0o.txt PreLayout/mean_pulsegate1o.cir
ngspice -b -o noiseMeanFirstStart/data1o.txt PreLayout/mean_pulsegate1o.cir
ngspice -b -o noiseMeanFirstStart/data2o.txt PreLayout/mean_pulsegate1o.cir
ngspice -b -o noiseMeanFirstStart/data3o.txt PreLayout/mean_pulsegate1o.cir
ngspice -b -o noiseMeanFirstStart/data4o.txt PreLayout/mean_pulsegate1o.cir
ngspice -b -o noiseMeanFirstStart/data5o.txt PreLayout/mean_pulsegate1o.cir
ngspice -b -o noiseMeanFirstStart/data6o.txt PreLayout/mean_pulsegate1o.cir
ngspice -b -o noiseMeanFirstStart/data7o.txt PreLayout/mean_pulsegate1o.cir
ngspice -b -o noiseMeanFirstStart/data8o.txt PreLayout/mean_pulsegate1o.cir
ngspice -b -o noiseMeanFirstStart/data9o.txt PreLayout/mean_pulsegate1o.cir
